name: composer update

on:
  #push:
  schedule:
    - cron: '0 0 * * *' #UTC

jobs:
  composer:
    uses: kawax/composer-workflow/.github/workflows/update.yml@v1
    with:
      php: 8.3
    secrets:
      token: ${{ secrets.ACTION_TOKEN }}
